(function () {
  const root = document.querySelector("#editor-root");
  const colors = [
    "#f3b8aa", "#a9d8b8", "#cbb8ec", "#f0d178", "#9dd8e8", "#efa9c5",
    "#c4dc8c", "#e9ba80", "#aebee8", "#91d6c7", "#e5a88e",
  ];
  const storageKey = "stars-remix:board-editor-draft:v1";
  const pendingPublishKey = "stars-remix:pending-community-publish:v1";
  let state = loadDraft();
  let result = null;
  let difficulty = null;
  let exported = null;
  let published = null;
  let publishing = false;
  let communityState = {
    status: "loading",
    enabled: false,
    user: null,
    message: "Checking publishing setup…",
  };
  let myBoardsOpen = false;
  let myBoardsLoading = false;
  let myBoards = [];
  let myBoardsError = "";
  let pendingPublishResumed = false;
  let worker = null;
  let busyMessage = "";
  let progress = null;
  let notice = null;
  let showSolution = false;
  let painting = false;
  let paintMode = "paint";
  let activePaintHouse = null;
  let selectedPaintHouse = null;

  function blankState(size = 9) {
    return {
      size,
      title: "",
      houses: Array.from({ length: size }, () => Array(size).fill(-1)),
    };
  }

  function loadDraft() {
    try {
      const saved = JSON.parse(localStorage.getItem(storageKey));
      const validGrid = [9, 10, 11].includes(saved.size) &&
        Array.isArray(saved.houses) && saved.houses.length === saved.size &&
        saved.houses.every((row) => Array.isArray(row) && row.length === saved.size &&
          row.every((house) => Number.isInteger(house) && house >= -1 && house < saved.size));
      if (validGrid) return saved;
    } catch {}
    return blankState();
  }

  function saveDraft() {
    try { localStorage.setItem(storageKey, JSON.stringify(state)); } catch {}
  }

  function render() {
    const displayHouses = result?.puzzle.houses ?? state.houses;
    const solutionKeys = new Set((showSolution ? result?.solution ?? [] : [])
      .map(({ row, col }) => `${row}:${col}`));
    const paintedCounts = Array.from({ length: state.size }, (_, house) =>
      state.houses.flat().filter((value) => value === house).length,
    );
    const nextUnusedHouse = paintedCounts.findIndex((count) => count === 0);
    const inspection = globalThis.StarsRemixEngine.inspectPartialHouses(state.houses);
    const assignedCount = state.houses.flat().filter((house) => house >= 0).length;
    const autoGeneratedCount = result
      ? state.houses.flat().filter((house) => house === -1).length
      : 0;
    const canExport = result && difficulty?.solved && difficulty.label !== "Incalculable" && state.title.trim() && !exported;
    const canPublish = result && difficulty?.solved && difficulty.label !== "Incalculable" &&
      state.title.trim() && communityState.enabled && !publishing && !published;
    const stage = published ? "published" : result && difficulty ? "test" : "design";

    root.innerHTML = `
      <main class="workshop-shell">
        <header class="workshop-header">
          <div class="workshop-brand">
            <a class="back-link" href="./index.html" aria-label="Back to StarsRemix">←</a>
            <div>
              <p class="eyebrow">StarsRemix</p>
              <h1>Board Workshop</h1>
            </div>
          </div>
          <nav class="workshop-steps" aria-label="Board creation progress">
            <span class="${stage === "design" ? "is-current" : "is-complete"}"><b>1</b> Design</span>
            <i aria-hidden="true"></i>
            <span class="${stage === "test" ? "is-current" : stage === "published" ? "is-complete" : ""}"><b>2</b> Test</span>
            <i aria-hidden="true"></i>
            <span class="${stage === "published" ? "is-current" : ""}"><b>3</b> Publish</span>
          </nav>
          ${accountControls()}
        </header>

        <section class="workspace">
          <div class="board-column">
            <div class="board-meta">
              <span><strong>${assignedCount}</strong> / ${state.size * state.size} tiles</span>
              <span><strong>${paintedCounts.filter(Boolean).length}</strong> / ${state.size} houses</span>
            </div>
            <div class="editor-board ${result ? "is-completed" : ""}" style="--board-size:${state.size}" aria-label="House editor board">
              ${displayHouses.map((row, rowIndex) => row.map((house, colIndex) => {
                const star = solutionKeys.has(`${rowIndex}:${colIndex}`);
                const blank = house === -1;
                const autoGenerated = Boolean(result) && state.houses[rowIndex][colIndex] === -1;
                return `<button class="editor-cell ${blank ? "is-blank" : ""} ${autoGenerated ? "is-auto-generated" : ""}" data-row="${rowIndex}" data-col="${colIndex}" style="${cellStyle(displayHouses, rowIndex, colIndex)}" aria-label="Row ${rowIndex + 1}, column ${colIndex + 1}${blank ? ", unassigned" : `, house ${house + 1}${autoGenerated ? ", automatically added" : ""}`}" ${published ? "disabled" : ""}>${star ? "<span class=\"solution-star\">★</span>" : ""}</button>`;
              }).join("")).join("")}
            </div>
            <p class="board-help"><span>Number keys choose a color</span><span>Right- or ⌘/Ctrl-drag to erase</span></p>
          </div>

          <aside class="tool-panel" aria-label="Board controls">
            <div class="panel-heading">
              <div>
                <p class="eyebrow">${stage === "design" ? "Step 1 · Design" : stage === "test" ? "Step 2 · Test passed" : "Step 3 · Published"}</p>
                <h2>${stage === "design" ? "Shape your constellation" : stage === "test" ? "Your board is ready" : "It’s out in the universe"}</h2>
              </div>
              <button class="text-button" id="clear-paint" ${autoGeneratedCount && !published ? "" : "disabled"} title="Remove automatically added houses">Clear generated</button>
            </div>

            <div class="palette-area">
              <div class="draft-fields">
                <label><span>Board title</span><input id="board-title" maxlength="80" placeholder="Give it a memorable name" value="${escapeHtml(state.title)}" ${published ? "disabled" : ""}></label>
                <label><span>Size</span><select id="board-size" aria-label="Board size" ${published ? "disabled" : ""}>${[9, 10, 11].map((size) => `<option value="${size}" ${state.size === size ? "selected" : ""}>${size} × ${size}</option>`).join("")}</select></label>
              </div>
              <p class="palette-label">House colors</p>
              <div class="house-palette" style="--palette-size:${state.size}" aria-label="House colors">
                ${paintedCounts.map((count, house) => `<button type="button" class="house-swatch ${selectedPaintHouse === house ? "is-selected" : selectedPaintHouse === null && nextUnusedHouse === house ? "is-next" : ""}" data-house="${house}" style="--swatch:${colors[house % colors.length]}" title="House ${house + 1} · ${count ? `${count} tiles` : "unused"} · click to select" aria-label="House ${house + 1}, ${count ? `${count} tiles` : "unused"}${selectedPaintHouse === house ? ", selected" : ""}" ${published ? "disabled" : ""}>${house + 1}</button>`).join("")}
              </div>
              ${legalityPanel(inspection)}
            </div>

            <div class="feedback-area" aria-live="polite">
              ${busyMessage ? `<div class="progress-card"><span class="spinner"></span><div><strong>${escapeHtml(busyMessage)}</strong><small>${escapeHtml(progress ?? "Working…")}</small></div></div>` : ""}
              ${notice ? noticePanel() : ""}
              ${result && difficulty ? resultPanel() : ""}
              ${published ? `<p class="published-note"><strong>Published to the community library.</strong> Players can find “${escapeHtml(published.entry.puzzle.title)}” under ${escapeHtml(published.entry.difficulty.label)}.</p>` : ""}
              ${exported ? `<p class="published-note">Downloaded <strong>${escapeHtml(exported.filename)}</strong>.</p>` : ""}
            </div>

            <div class="action-bar">
              ${stage === "design" ? `
                <button class="button primary" id="complete-board" ${worker ? "disabled" : ""}>${worker ? "Testing your board…" : "Finish & test board"}</button>
                ${worker ? '<button class="button secondary" id="cancel-work">Cancel</button>' : ""}
                <button class="button text-action" id="new-board">Start over</button>
              ` : stage === "test" ? `
                <button class="button publish" id="publish-board" ${canPublish ? "" : "disabled"}>${publishButtonLabel()}</button>
                <button class="button text-action" id="complete-board" ${worker ? "disabled" : ""}>Try another completion</button>
                ${!communityState.enabled ? `<p class="publish-help">${escapeHtml(communityState.message || "Community publishing is not configured for this site.")}</p>` : ""}
              ` : `
                <button class="button primary" id="play-published">Play this board</button>
                <button class="button secondary" id="new-after-publish">Create another</button>
              `}
            </div>
            <details class="debug-tools">
              <summary>Debug tools</summary>
              <div>
                <label class="solution-toggle"><input id="show-solution" type="checkbox" ${showSolution ? "checked" : ""} ${result ? "" : "disabled"}> Show solution stars</label>
                <button class="text-button" id="export-board" ${canExport ? "" : "disabled"}>${exported ? "Board JSON downloaded ✓" : "Download board JSON"}</button>
              </div>
            </details>
          </aside>
        </section>
      </main>
      ${myBoardsOpen ? renderMyBoards() : ""}`;
    bindEvents();
  }

  function accountControls() {
    if (!communityState.user) return "";
    const displayName = communityState.user.name || communityState.user.email || "Signed-in player";
    return `<div class="account-controls">
      <span class="account-avatar" aria-hidden="true">${escapeHtml(displayName.slice(0, 1).toUpperCase())}</span>
      <span class="account-name">${escapeHtml(displayName)}</span>
      <button class="text-button" id="my-boards" type="button">My boards</button>
      <button class="text-button subdued" id="sign-out" type="button">Sign out</button>
    </div>`;
  }

  function publishButtonLabel() {
    if (publishing) return "Publishing…";
    if (published) return "Published ✓";
    if (communityState.status === "loading") return "Preparing publishing…";
    if (!communityState.enabled) return "Publishing unavailable";
    return "Publish board";
  }

  function renderMyBoards() {
    return `<div class="boards-overlay" role="dialog" aria-modal="true" aria-labelledby="my-boards-title">
      <section class="boards-dialog">
        <header>
          <div>
            <p class="eyebrow">Community library</p>
            <h2 id="my-boards-title">My published boards</h2>
          </div>
          <button class="boards-close" id="close-my-boards" type="button" aria-label="Close my boards">×</button>
        </header>
        <div class="my-board-list">
          ${myBoardsLoading ? `<div class="boards-empty"><span class="spinner"></span><p>Loading your boards…</p></div>` : ""}
          ${myBoardsError ? `<div class="notice error"><strong>${escapeHtml(myBoardsError)}</strong></div>` : ""}
          ${!myBoardsLoading && !myBoardsError && !myBoards.length ? `<div class="boards-empty"><p>You have not published a board yet.</p><small>Complete one here, then choose Publish board.</small></div>` : ""}
          ${myBoards.map(({ id, entry }) => `<article class="my-board-row">
            <div>
              <strong>${escapeHtml(entry.puzzle.title)}</strong>
              <small>${entry.puzzle.size}×${entry.puzzle.size} · ${escapeHtml(entry.difficulty.label)} · ${formatPublishedDate(entry.publishedAt)}</small>
            </div>
            <button class="text-button destructive" type="button" data-delete-board="${escapeHtml(id)}">Remove</button>
          </article>`).join("")}
        </div>
      </section>
    </div>`;
  }

  function legalityPanel(inspection) {
    if (inspection.valid) {
      const remaining = inspection.missingHouseIds.length;
      return `<div class="legality-card is-valid" role="status"><span class="status-dot"></span><strong>Shape is viable</strong><p>${remaining ? `${remaining} ${remaining === 1 ? "house" : "houses"} left` : "Ready to complete"}</p></div>`;
    }
    return `<div class="legality-card is-invalid" role="alert"><span class="status-dot"></span><strong>Needs attention</strong><ul>${inspection.issues.map((issue) => `<li>${escapeHtml(issue.message)}</li>`).join("")}</ul></div>`;
  }

  function noticePanel() {
    return `<div class="notice ${notice.kind}" role="status"><strong>${escapeHtml(notice.message)}</strong>${notice.details?.length ? `<ul>${notice.details.map((detail) => `<li>${escapeHtml(detail)}</li>`).join("")}</ul>` : ""}</div>`;
  }

  function resultPanel() {
    const techniqueSummary = (difficulty.techniqueCounts ?? []).map((technique) => `
      <li>
        <span>${escapeHtml(technique.title)}</span>
        <span class="technique-tier">${escapeHtml(technique.tier)}</span>
        <strong>×${technique.count}</strong>
      </li>
    `).join("");
    const logicalSteps = (difficulty.steps ?? []).map((step) => `
      <li class="difficulty-step${step.bigTicket ? " is-big-ticket" : ""}">
        <div><strong>${step.number}. ${escapeHtml(step.title)}</strong><span>${escapeHtml(step.tier)}</span></div>
        <p>${step.moves.map(formatDifficultyMove).join(", ")}</p>
      </li>
    `).join("");
    const bigTicketCount = difficulty.bigTicketCount ?? 0;
    const logicalStepCount = difficulty.logicalSteps ?? difficulty.steps?.length ?? 0;

    return `<div class="result-card">
      <p class="result-kicker">Board difficulty</p>
      <div class="result-summary">
        <div class="difficulty-badge ${difficulty.label.toLowerCase().replaceAll(" ", "-")}">${escapeHtml(difficulty.label)}</div>
        <span>${bigTicketCount} big-ticket deduction${bigTicketCount === 1 ? "" : "s"} · weighted score ${difficulty.score}</span>
      </div>
      ${techniqueSummary
        ? `<p class="technique-heading">Techniques required · ${logicalStepCount} logical steps</p>
          <ul class="technique-summary">${techniqueSummary}</ul>
          <details class="difficulty-details">
            <summary>Every logical move (${logicalStepCount})</summary>
            <ol>${logicalSteps}</ol>
          </details>`
        : `<p class="technique-unavailable">Technique details are unavailable for this previously published board.</p>`}
    </div>`;
  }

  function formatDifficultyMove(move) {
    const token = move.state === "star" ? "★" : "×";
    return `${token} R${move.row + 1}C${move.col + 1}`;
  }

  function cellStyle(houses, row, col) {
    const house = houses[row][col];
    if (house === -1) return "";
    const edges = globalThis.StarsRemixEngine.getHouseEdges(houses, row, col);
    const thick = "3px solid #25231f";
    const thin = "1px solid rgba(37,35,31,.22)";
    return [
      `--cell-color:${colors[house % colors.length]}`,
      `border-top:${edges.top ? thick : thin}`,
      `border-right:${edges.right ? thick : thin}`,
      `border-bottom:${edges.bottom ? thick : thin}`,
      `border-left:${edges.left ? thick : thin}`,
    ].join(";");
  }

  function bindEvents() {
    document.querySelector("#board-title").addEventListener("input", (event) => {
      state.title = event.target.value;
      exported = null;
      published = null;
      saveDraft();
      const exportButton = document.querySelector("#export-board");
      if (exportButton) {
        exportButton.disabled = !(result && difficulty?.solved && difficulty.label !== "Incalculable" && state.title.trim());
      }
      const publishButton = document.querySelector("#publish-board");
      if (publishButton) {
        publishButton.disabled = !(result && difficulty?.solved && difficulty.label !== "Incalculable" &&
          state.title.trim() && communityState.enabled && !publishing);
      }
    });
    document.querySelector("#board-size").addEventListener("change", (event) => {
      const size = Number(event.target.value);
      state = blankState(size);
      selectedPaintHouse = null;
      resetResult();
      saveDraft();
      render();
    });
    document.querySelector("#new-board")?.addEventListener("click", () => {
      if (state.houses.flat().some((house) => house >= 0) && !confirm("Start over with a totally blank board?")) return;
      state = blankState(state.size);
      selectedPaintHouse = null;
      resetResult();
      saveDraft();
      render();
    });
    document.querySelector("#clear-paint").addEventListener("click", () => {
      stopWorker();
      resetResult();
      render();
    });
    document.querySelectorAll(".house-swatch").forEach((swatch) => {
      swatch.addEventListener("click", () => {
        selectedPaintHouse = Number(swatch.dataset.house);
        notice = null;
        render();
      });
    });
    document.querySelectorAll(".editor-cell").forEach((cell) => {
      cell.addEventListener("pointerdown", (event) => {
        if (event.button !== 0 && event.button !== 2) return;
        event.preventDefault();
        if (result) resetResult();
        const row = Number(cell.dataset.row);
        const col = Number(cell.dataset.col);
        paintMode = event.button === 2 || event.ctrlKey || event.metaKey ? "erase" : "paint";
        if (paintMode === "paint") {
          activePaintHouse = selectedPaintHouse ?? globalThis.StarsRemixEngine.getPaintHouseId(state.houses, row, col);
          if (activePaintHouse === -1) {
            painting = false;
            notice = { kind: "error", message: "All house colors are already in use. Start on an existing house to extend it, or erase a house first." };
            render();
            return;
          }
        } else {
          activePaintHouse = null;
        }
        painting = true;
        paintCell(row, col);
      });
      cell.addEventListener("pointerenter", (event) => {
        if (!painting || (event.buttons & 3) === 0) return;
        paintCell(Number(cell.dataset.row), Number(cell.dataset.col));
      });
      cell.addEventListener("contextmenu", (event) => event.preventDefault());
    });
    document.querySelector("#complete-board")?.addEventListener("click", completeBoard);
    document.querySelector("#cancel-work")?.addEventListener("click", cancelWork);
    document.querySelector("#show-solution")?.addEventListener("change", (event) => {
      showSolution = event.target.checked;
      render();
    });
    document.querySelector("#export-board")?.addEventListener("click", exportBoard);
    document.querySelector("#publish-board")?.addEventListener("click", publishBoard);
    document.querySelector("#google-sign-in")?.addEventListener("click", beginGoogleSignIn);
    document.querySelector("#sign-out")?.addEventListener("click", signOut);
    document.querySelector("#my-boards")?.addEventListener("click", openMyBoards);
    document.querySelector("#close-my-boards")?.addEventListener("click", () => {
      myBoardsOpen = false;
      render();
    });
    document.querySelectorAll("[data-delete-board]").forEach((button) => {
      button.addEventListener("click", () => removePublishedBoard(button.dataset.deleteBoard));
    });
    document.querySelector("#new-after-publish")?.addEventListener("click", () => {
      state = blankState(state.size);
      selectedPaintHouse = null;
      resetResult();
      saveDraft();
      render();
    });
    document.querySelector("#play-published")?.addEventListener("click", () => {
      if (!published?.entry?.puzzle?.id) return;
      window.location.href = `./index.html?board=${encodeURIComponent(published.entry.puzzle.id)}`;
    });
  }

  function paintCell(row, col) {
    if (result) resetResult();
    const current = state.houses[row][col];
    if (paintMode === "paint" && current >= 0 && current !== activePaintHouse) return;
    const value = paintMode === "erase" ? -1 : activePaintHouse;
    if (state.houses[row][col] === value) return;
    state.houses[row][col] = value;
    notice = null;
    saveDraft();
    render();
  }

  function completeBoard() {
    notice = null;
    exported = null;
    const inspection = globalThis.StarsRemixEngine.inspectPartialHouses(state.houses);
    if (!inspection.valid) {
      notice = {
        kind: "error",
        message: "This draft cannot be completed yet:",
        details: inspection.issues.map((issue) => issue.message),
      };
      render();
      return;
    }
    try {
      worker = new Worker(new URL("./src/editor/editor-worker.js", document.baseURI));
    } catch (error) {
      startCompatibilityCompletion();
      return;
    }
    const completionWorker = worker;
    busyMessage = "Constructing the missing houses…";
    progress = "Beginning the search";
    completionWorker.addEventListener("message", (event) => {
      if (worker === completionWorker) handleWorkerMessage(event);
    });
    completionWorker.addEventListener("error", (event) => {
      if (worker !== completionWorker) return;
      event.preventDefault();
      startCompatibilityCompletion();
    });
    completionWorker.addEventListener("messageerror", () => {
      if (worker === completionWorker) {
        startCompatibilityCompletion();
      }
    });
    completionWorker.postMessage({
      type: "complete",
      houses: state.houses,
      title: state.title.trim() || "Untitled Handmade Board",
      seed: `editor-${Date.now()}-${Math.random()}`,
      maxAttempts: state.size === 11 ? 3_000 : 4_000,
    });
    render();
  }

  function handleWorkerMessage(event) {
    const message = event.data;
    if (message.type === "startup-error") {
      startCompatibilityCompletion();
    } else if (message.type === "generation-progress") {
      const candidateLabel = message.progress.candidateMaximum > 1 ? `Candidate ${message.progress.candidate} of ${message.progress.candidateMaximum} · ` : "";
      progress = `${candidateLabel}attempt ${message.progress.attempt} of ${message.progress.maximum}`;
      render();
    } else if (message.type === "analysis-started") {
      result = message.generated;
      busyMessage = "Checking logical difficulty…";
      progress = `${message.candidateMaximum > 1 ? `Candidate ${message.candidate} of ${message.candidateMaximum} · ` : ""}testing the basic rules`;
      render();
    } else if (message.type === "difficulty-progress") {
      const detail = message.progress.technique || "logical techniques";
      const candidateLabel = message.progress.candidateMaximum > 1 ? `Candidate ${message.progress.candidate} of ${message.progress.candidateMaximum} · ` : "";
      progress = `${candidateLabel}${message.progress.percent ?? 0}% · ${detail}`;
      render();
    } else if (message.type === "candidate-rejected") {
      result = null;
      busyMessage = "Trying a more logically solvable completion…";
      progress = `The unique candidate ${message.candidate} of ${message.candidateMaximum} was incalculable`;
      render();
    } else if (message.type === "completed") {
      result = message.generated;
      difficulty = message.difficulty;
      if (!difficulty.solved || difficulty.label === "Incalculable") {
        notice = { kind: "error", message: "The board is unique, but the logical analyzer could not finish it. Try another completion." };
      } else {
        notice = { kind: "success", message: "Unique solution confirmed. This board is ready to publish." };
      }
      stopWorker();
      render();
    } else if (message.type === "error") {
      finishWithError(message.message);
    }
  }

  function startCompatibilityCompletion() {
    stopWorker();
    let cancelled = false;
    const compatibilityJob = {
      terminate() { cancelled = true; },
    };
    worker = compatibilityJob;
    busyMessage = "Constructing the missing houses…";
    progress = "Using browser compatibility mode";
    render();

    setTimeout(async () => {
      try {
        const boardIsFullyPainted = state.houses.every((row) => row.every((house) => house >= 0));
        const boardIsBlank = state.houses.every((row) => row.every((house) => house === -1));
        const candidateMaximum = boardIsFullyPainted ? 1 : boardIsBlank ? 12 : 8;
        const seed = `editor-${Date.now()}-${Math.random()}`;
        const maxAttempts = state.size === 11 ? 3_000 : 4_000;
        let lastResult = null;

        for (let candidate = 1; candidate <= candidateMaximum && !cancelled; candidate += 1) {
          const generated = globalThis.StarsRemixEngine.completePuzzleFromHouses(state.houses, {
            title: state.title.trim() || "Untitled Handmade Board",
            seed: `${seed}-candidate-${candidate}`,
            maxAttempts,
            onProgress(update) {
              progress = `${candidateMaximum > 1 ? `Candidate ${candidate} of ${candidateMaximum} · ` : ""}attempt ${update.attempt} of ${update.maximum}`;
            },
          });
          if (cancelled) return;

          result = generated;
          busyMessage = "Checking logical difficulty…";
          progress = `${candidateMaximum > 1 ? `Candidate ${candidate} of ${candidateMaximum} · ` : ""}testing the basic rules`;
          render();
          const report = await globalThis.StarsRemixHints.analyzeDifficulty(generated.puzzle, {
            onProgress(update) {
              progress = `${candidateMaximum > 1 ? `Candidate ${candidate} of ${candidateMaximum} · ` : ""}${update.percent ?? 0}% · ${update.technique || "logical techniques"}`;
            },
            yieldControl: () => new Promise((resolve) => setTimeout(resolve, 0)),
          });
          if (cancelled) return;

          lastResult = { generated, report };
          if (report.solved && report.label !== "Incalculable") break;
          if (candidate < candidateMaximum) {
            result = null;
            busyMessage = "Trying a more logically solvable completion…";
            progress = `The unique candidate ${candidate} of ${candidateMaximum} was incalculable`;
            render();
            await new Promise((resolve) => setTimeout(resolve, 0));
          }
        }

        if (cancelled || worker !== compatibilityJob) return;
        const { generated, report } = lastResult;
        handleWorkerMessage({
          data: {
            type: "completed",
            generated,
            difficulty: { ...report, logicalSteps: report.steps.length },
          },
        });
      } catch (error) {
        if (!cancelled && worker === compatibilityJob) {
          finishWithError(error instanceof Error ? error.message : "Unable to complete this board.");
        }
      }
    }, 0);
  }

  function exportBoard() {
    if (!result || !difficulty) return;
    const title = state.title.trim();
    if (!title) {
      notice = { kind: "error", message: "Give the board a title before exporting." };
      render();
      return;
    }

    try {
      const id = `handmade-${boardSlug(title)}-${Date.now().toString(36)}`;
      const entry = {
        puzzle: { ...result.puzzle, id, title },
        solution: result.solution,
        difficulty: {
          label: difficulty.label,
          score: difficulty.score,
          bigTicketCount: difficulty.bigTicketCount,
          logicalSteps: difficulty.logicalSteps,
        },
        source: "handmade",
      };
      const filename = `${id}.json`;
      downloadJson(filename, entry);
      exported = { filename, entry };
      result.puzzle.id = id;
      result.puzzle.title = title;
      notice = { kind: "success", message: "Board JSON downloaded." };
    } catch (error) {
      notice = { kind: "error", message: error instanceof Error ? error.message : "Unable to export this board." };
    }
    render();
  }

  async function publishBoard() {
    if (!result || !difficulty || publishing || published) return;
    const entry = makeShareableEntry();
    if (!entry) return;

    if (!communityState.user) {
      try {
        sessionStorage.setItem(pendingPublishKey, JSON.stringify(entry));
        notice = { kind: "info", message: "Taking you to Google. Your completed board will be waiting when you return." };
        render();
        await beginGoogleSignIn("./editor.html?publish=1");
      } catch (error) {
        notice = { kind: "error", message: error instanceof Error ? error.message : "Unable to start Google sign-in." };
        render();
      }
      return;
    }
    await submitPublishedBoard(entry);
  }

  function makeShareableEntry() {
    const title = state.title.trim();
    if (!title) {
      notice = { kind: "error", message: "Give the board a title before publishing." };
      render();
      return null;
    }
    return {
      puzzle: { ...result.puzzle, title },
      solution: result.solution,
      difficulty: {
        label: difficulty.label,
        score: difficulty.score,
        bigTicketCount: difficulty.bigTicketCount,
        logicalSteps: difficulty.logicalSteps,
      },
    };
  }

  async function submitPublishedBoard(entry) {
    publishing = true;
    notice = { kind: "info", message: "Verifying your board once more before publishing…" };
    render();
    try {
      const response = await globalThis.StarsRemixCommunity.publishBoard(entry);
      applyPublishedBoard(response.board);
      try { sessionStorage.removeItem(pendingPublishKey); } catch {}
    } catch (error) {
      notice = { kind: "error", message: error instanceof Error ? error.message : "Unable to publish this board." };
    } finally {
      publishing = false;
      render();
    }
  }

  function applyPublishedBoard(board) {
    published = board;
    result = {
      puzzle: board.entry.puzzle,
      solution: board.entry.solution,
      diagnostics: result?.diagnostics ?? { attempts: "—" },
    };
    difficulty = { ...difficulty, ...board.entry.difficulty, solved: true };
    state.title = board.entry.puzzle.title;
    notice = { kind: "success", message: "Published! Your board is now in the community library." };
    saveDraft();
  }

  async function beginGoogleSignIn(callback = "./editor.html") {
    try {
      await globalThis.StarsRemixCommunity.signInWithGoogle(callback);
    } catch (error) {
      notice = { kind: "error", message: error instanceof Error ? error.message : "Unable to start Google sign-in." };
      render();
    }
  }

  async function signOut() {
    try {
      await globalThis.StarsRemixCommunity.signOut();
      myBoardsOpen = false;
      notice = { kind: "info", message: "Signed out. Your editor draft is still saved on this device." };
    } catch (error) {
      notice = { kind: "error", message: error instanceof Error ? error.message : "Unable to sign out." };
    }
    render();
  }

  async function openMyBoards() {
    myBoardsOpen = true;
    myBoardsLoading = true;
    myBoardsError = "";
    render();
    try {
      const response = await globalThis.StarsRemixCommunity.listMyBoards();
      myBoards = response.boards ?? [];
    } catch (error) {
      myBoardsError = error instanceof Error ? error.message : "Unable to load your boards.";
    } finally {
      myBoardsLoading = false;
      render();
    }
  }

  async function removePublishedBoard(id) {
    const board = myBoards.find((candidate) => candidate.id === id);
    if (!board || !confirm(`Remove “${board.entry.puzzle.title}” from the community library?`)) return;
    try {
      await globalThis.StarsRemixCommunity.deleteBoard(id);
      myBoards = myBoards.filter((candidate) => candidate.id !== id);
      if (published?.id === id) published = null;
      notice = { kind: "info", message: "Board removed from the community library." };
    } catch (error) {
      myBoardsError = error instanceof Error ? error.message : "Unable to remove that board.";
    }
    render();
  }

  async function resumePendingPublish() {
    if (pendingPublishResumed || !communityState.user) return;
    const url = new URL(window.location.href);
    if (url.searchParams.get("publish") !== "1") return;
    pendingPublishResumed = true;
    url.searchParams.delete("publish");
    history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`);
    try {
      const entry = JSON.parse(sessionStorage.getItem(pendingPublishKey) ?? "null");
      if (!entry?.puzzle) return;
      await submitPublishedBoard(entry);
    } catch {
      notice = { kind: "error", message: "Your sign-in succeeded, but the completed board could not be restored. Complete it once more to publish." };
      render();
    }
  }

  function downloadJson(filename, value) {
    const blob = new Blob([`${JSON.stringify(value, null, 2)}\n`], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.append(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 0);
  }

  function boardSlug(value) {
    return globalThis.StarsRemixEngine.slug(value, { maxLength: 48, fallback: "untitled" });
  }

  function cancelWork() {
    stopWorker();
    result = null;
    difficulty = null;
    notice = { kind: "info", message: "Completion cancelled. Your painted houses are unchanged." };
    render();
  }

  function finishWithError(message) {
    stopWorker();
    result = null;
    difficulty = null;
    notice = { kind: "error", message };
    render();
  }

  function stopWorker() {
    worker?.terminate();
    worker = null;
    busyMessage = "";
    progress = null;
  }

  function resetResult() {
    result = null;
    difficulty = null;
    exported = null;
    published = null;
    showSolution = false;
    notice = null;
  }

  function escapeHtml(value) {
    return globalThis.StarsRemixEngine.escapeHtml(value);
  }

  function formatPublishedDate(value) {
    try {
      return new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" })
        .format(new Date(value));
    } catch {
      return "Published";
    }
  }

  window.addEventListener("pointerup", () => { painting = false; activePaintHouse = null; });
  window.addEventListener("blur", () => { painting = false; activePaintHouse = null; });
  window.addEventListener("keydown", (event) => {
    if (event.ctrlKey || event.metaKey || event.altKey || event.target.matches("input, select, textarea, [contenteditable]")) return;
    if (!/^\d$/.test(event.key)) return;
    const house = event.key === "0" ? 9 : Number(event.key) - 1;
    if (house >= state.size) return;
    event.preventDefault();
    selectedPaintHouse = house;
    notice = null;
    render();
  });
  if (globalThis.StarsRemixCommunity) {
    communityState = globalThis.StarsRemixCommunity.getState();
    window.addEventListener("starsremix:community-auth", (event) => {
      communityState = event.detail;
      render();
      resumePendingPublish();
    });
    globalThis.StarsRemixCommunity.ready.then(() => {
      communityState = globalThis.StarsRemixCommunity.getState();
      render();
      resumePendingPublish();
    });
  }
  render();
})();
