(function () {
  const root = document.querySelector("#editor-root");
  const colors = [
    "#f3b8aa", "#a9d8b8", "#cbb8ec", "#f0d178", "#9dd8e8", "#efa9c5",
    "#c4dc8c", "#e9ba80", "#aebee8", "#91d6c7", "#e5a88e",
  ];
  const storageKey = "stars-remix:board-editor-draft:v1";
  let state = loadDraft();
  let result = null;
  let difficulty = null;
  let exported = null;
  let worker = null;
  let busyMessage = "";
  let progress = null;
  let notice = null;
  let showSolution = false;
  let painting = false;
  let paintMode = "paint";
  let activePaintHouse = null;
  let selectedPaintHouse = null;

  function blankState(size = 9) {
    return {
      size,
      title: "",
      houses: Array.from({ length: size }, () => Array(size).fill(-1)),
    };
  }

  function loadDraft() {
    try {
      const saved = JSON.parse(localStorage.getItem(storageKey));
      const validGrid = [9, 10, 11].includes(saved.size) &&
        Array.isArray(saved.houses) && saved.houses.length === saved.size &&
        saved.houses.every((row) => Array.isArray(row) && row.length === saved.size &&
          row.every((house) => Number.isInteger(house) && house >= -1 && house < saved.size));
      if (validGrid) return saved;
    } catch {}
    return blankState();
  }

  function saveDraft() {
    try { localStorage.setItem(storageKey, JSON.stringify(state)); } catch {}
  }

  function render() {
    const displayHouses = result?.puzzle.houses ?? state.houses;
    const solutionKeys = new Set((showSolution ? result?.solution ?? [] : [])
      .map(({ row, col }) => `${row}:${col}`));
    const paintedCounts = Array.from({ length: state.size }, (_, house) =>
      state.houses.flat().filter((value) => value === house).length,
    );
    const nextUnusedHouse = paintedCounts.findIndex((count) => count === 0);
    const inspection = globalThis.StarsRemixEngine.inspectPartialHouses(state.houses);
    const assignedCount = state.houses.flat().filter((house) => house >= 0).length;
    const autoGeneratedCount = result
      ? state.houses.flat().filter((house) => house === -1).length
      : 0;
    const canExport = result && difficulty?.solved && difficulty.label !== "Incalculable" && state.title.trim() && !exported;

    root.innerHTML = `
      <main class="workshop-shell">
        <header class="workshop-header">
          <div class="workshop-brand">
            <a class="back-link" href="./index.html" aria-label="Back to StarsRemix">←</a>
            <div>
              <p class="eyebrow">StarsRemix</p>
              <h1>Board editor</h1>
            </div>
          </div>
          <div class="draft-fields">
            <label><span>Title</span><input id="board-title" maxlength="80" placeholder="Untitled board" value="${escapeHtml(state.title)}"></label>
            <label><span>Size</span><select id="board-size" aria-label="Board size">${[9, 10, 11].map((size) => `<option value="${size}" ${state.size === size ? "selected" : ""}>${size} × ${size}</option>`).join("")}</select></label>
          </div>
        </header>

        <section class="workspace">
          <div class="board-column">
            <div class="board-meta">
              <span><strong>${assignedCount}</strong> / ${state.size * state.size} tiles</span>
              <span><strong>${paintedCounts.filter(Boolean).length}</strong> / ${state.size} houses</span>
            </div>
            <div class="editor-board ${result ? "is-completed" : ""}" style="--board-size:${state.size}" aria-label="House editor board">
              ${displayHouses.map((row, rowIndex) => row.map((house, colIndex) => {
                const star = solutionKeys.has(`${rowIndex}:${colIndex}`);
                const blank = house === -1;
                const autoGenerated = Boolean(result) && state.houses[rowIndex][colIndex] === -1;
                return `<button class="editor-cell ${blank ? "is-blank" : ""} ${autoGenerated ? "is-auto-generated" : ""}" data-row="${rowIndex}" data-col="${colIndex}" style="${cellStyle(displayHouses, rowIndex, colIndex)}" aria-label="Row ${rowIndex + 1}, column ${colIndex + 1}${blank ? ", unassigned" : `, house ${house + 1}${autoGenerated ? ", automatically added" : ""}`}">${star ? "<span class=\"solution-star\">★</span>" : ""}</button>`;
              }).join("")).join("")}
            </div>
            <p class="board-help"><span>Number keys choose a color</span><span>Right- or ⌘/Ctrl-drag to erase</span></p>
          </div>

          <aside class="tool-panel" aria-label="Board controls">
            <div class="panel-heading">
              <div>
                <p class="eyebrow">House palette</p>
                <h2>Paint your regions</h2>
              </div>
              <button class="text-button" id="clear-paint" ${autoGeneratedCount ? "" : "disabled"} title="Remove automatically added houses">Clear generated</button>
            </div>

            <div class="palette-area">
              <div class="house-palette" style="--palette-size:${state.size}" aria-label="House colors">
                ${paintedCounts.map((count, house) => `<button type="button" class="house-swatch ${selectedPaintHouse === house ? "is-selected" : selectedPaintHouse === null && nextUnusedHouse === house ? "is-next" : ""}" data-house="${house}" style="--swatch:${colors[house % colors.length]}" title="House ${house + 1} · ${count ? `${count} tiles` : "unused"} · click to select" aria-label="House ${house + 1}, ${count ? `${count} tiles` : "unused"}${selectedPaintHouse === house ? ", selected" : ""}">${house + 1}</button>`).join("")}
              </div>
              ${legalityPanel(inspection)}
            </div>

            <div class="feedback-area" aria-live="polite">
              ${busyMessage ? `<div class="progress-card"><span class="spinner"></span><div><strong>${escapeHtml(busyMessage)}</strong><small>${escapeHtml(progress ?? "Working…")}</small></div></div>` : ""}
              ${notice ? noticePanel() : ""}
              ${result && difficulty ? resultPanel() : ""}
              ${exported ? `<p class="published-note">Downloaded <strong>${escapeHtml(exported.filename)}</strong>. Import it into the project to add it to gameplay.</p>` : ""}
            </div>

            <div class="action-bar">
              <button class="button primary" id="complete-board" ${worker ? "disabled" : ""}>${result ? "Try another" : "Complete board"}</button>
              ${worker ? '<button class="button secondary" id="cancel-work">Cancel</button>' : ""}
              <button class="button publish" id="export-board" ${canExport ? "" : "disabled"}>${exported ? "Downloaded ✓" : "Export board"}</button>
              <button class="icon-button" id="new-board" title="New blank board" aria-label="New blank board">↻</button>
            </div>
          </aside>
        </section>
      </main>`;
    bindEvents();
  }

  function legalityPanel(inspection) {
    if (inspection.valid) {
      const remaining = inspection.missingHouseIds.length;
      return `<div class="legality-card is-valid" role="status"><span class="status-dot"></span><strong>Shape is viable</strong><p>${remaining ? `${remaining} ${remaining === 1 ? "house" : "houses"} left` : "Ready to complete"}</p></div>`;
    }
    return `<div class="legality-card is-invalid" role="alert"><span class="status-dot"></span><strong>Needs attention</strong><ul>${inspection.issues.map((issue) => `<li>${escapeHtml(issue.message)}</li>`).join("")}</ul></div>`;
  }

  function noticePanel() {
    return `<div class="notice ${notice.kind}" role="status"><strong>${escapeHtml(notice.message)}</strong>${notice.details?.length ? `<ul>${notice.details.map((detail) => `<li>${escapeHtml(detail)}</li>`).join("")}</ul>` : ""}</div>`;
  }

  function resultPanel() {
    return `<div class="result-card">
      <div class="result-summary"><div class="difficulty-badge ${difficulty.label.toLowerCase().replaceAll(" ", "-")}">${escapeHtml(difficulty.label)}</div><span>Score <strong>${difficulty.score}</strong></span><span>Steps <strong>${difficulty.logicalSteps}</strong></span><span>Advanced <strong>${difficulty.bigTicketCount}</strong></span><span>Attempts <strong>${result.diagnostics.attempts}</strong></span></div>
      <label class="solution-toggle"><input id="show-solution" type="checkbox" ${showSolution ? "checked" : ""}> Show solution stars</label>
    </div>`;
  }

  function cellStyle(houses, row, col) {
    const house = houses[row][col];
    if (house === -1) return "";
    const thick = "3px solid #25231f";
    const thin = "1px solid rgba(37,35,31,.22)";
    return [
      `--cell-color:${colors[house % colors.length]}`,
      `border-top:${row === 0 || houses[row - 1][col] !== house ? thick : thin}`,
      `border-right:${col === state.size - 1 || houses[row][col + 1] !== house ? thick : thin}`,
      `border-bottom:${row === state.size - 1 || houses[row + 1][col] !== house ? thick : thin}`,
      `border-left:${col === 0 || houses[row][col - 1] !== house ? thick : thin}`,
    ].join(";");
  }

  function bindEvents() {
    document.querySelector("#board-title").addEventListener("input", (event) => {
      state.title = event.target.value;
      exported = null;
      saveDraft();
      const exportButton = document.querySelector("#export-board");
      if (exportButton) {
        exportButton.disabled = !(result && difficulty?.solved && difficulty.label !== "Incalculable" && state.title.trim());
      }
    });
    document.querySelector("#board-size").addEventListener("change", (event) => {
      const size = Number(event.target.value);
      state = blankState(size);
      selectedPaintHouse = null;
      resetResult();
      saveDraft();
      render();
    });
    document.querySelector("#new-board").addEventListener("click", () => {
      if (state.houses.flat().some((house) => house >= 0) && !confirm("Start over with a totally blank board?")) return;
      state = blankState(state.size);
      selectedPaintHouse = null;
      resetResult();
      saveDraft();
      render();
    });
    document.querySelector("#clear-paint").addEventListener("click", () => {
      stopWorker();
      resetResult();
      render();
    });
    document.querySelectorAll(".house-swatch").forEach((swatch) => {
      swatch.addEventListener("click", () => {
        selectedPaintHouse = Number(swatch.dataset.house);
        notice = null;
        render();
      });
    });
    document.querySelectorAll(".editor-cell").forEach((cell) => {
      cell.addEventListener("pointerdown", (event) => {
        if (event.button !== 0 && event.button !== 2) return;
        event.preventDefault();
        if (result) resetResult();
        const row = Number(cell.dataset.row);
        const col = Number(cell.dataset.col);
        paintMode = event.button === 2 || event.ctrlKey || event.metaKey ? "erase" : "paint";
        if (paintMode === "paint") {
          activePaintHouse = selectedPaintHouse ?? globalThis.StarsRemixEngine.getPaintHouseId(state.houses, row, col);
          if (activePaintHouse === -1) {
            painting = false;
            notice = { kind: "error", message: "All house colors are already in use. Start on an existing house to extend it, or erase a house first." };
            render();
            return;
          }
        } else {
          activePaintHouse = null;
        }
        painting = true;
        paintCell(row, col);
      });
      cell.addEventListener("pointerenter", (event) => {
        if (!painting || (event.buttons & 3) === 0) return;
        paintCell(Number(cell.dataset.row), Number(cell.dataset.col));
      });
      cell.addEventListener("contextmenu", (event) => event.preventDefault());
    });
    document.querySelector("#complete-board").addEventListener("click", completeBoard);
    document.querySelector("#cancel-work")?.addEventListener("click", cancelWork);
    document.querySelector("#show-solution")?.addEventListener("change", (event) => {
      showSolution = event.target.checked;
      render();
    });
    document.querySelector("#export-board").addEventListener("click", exportBoard);
  }

  function paintCell(row, col) {
    if (result) resetResult();
    const current = state.houses[row][col];
    if (paintMode === "paint" && current >= 0 && current !== activePaintHouse) return;
    const value = paintMode === "erase" ? -1 : activePaintHouse;
    if (state.houses[row][col] === value) return;
    state.houses[row][col] = value;
    notice = null;
    saveDraft();
    render();
  }

  function completeBoard() {
    notice = null;
    exported = null;
    const inspection = globalThis.StarsRemixEngine.inspectPartialHouses(state.houses);
    if (!inspection.valid) {
      notice = {
        kind: "error",
        message: "This draft cannot be completed yet:",
        details: inspection.issues.map((issue) => issue.message),
      };
      render();
      return;
    }
    try {
      worker = new Worker(new URL("./src/editor/editor-worker.js", document.baseURI));
    } catch (error) {
      startCompatibilityCompletion();
      return;
    }
    const completionWorker = worker;
    busyMessage = "Constructing the missing houses…";
    progress = "Beginning the search";
    completionWorker.addEventListener("message", (event) => {
      if (worker === completionWorker) handleWorkerMessage(event);
    });
    completionWorker.addEventListener("error", (event) => {
      if (worker !== completionWorker) return;
      event.preventDefault();
      startCompatibilityCompletion();
    });
    completionWorker.addEventListener("messageerror", () => {
      if (worker === completionWorker) {
        startCompatibilityCompletion();
      }
    });
    completionWorker.postMessage({
      type: "complete",
      houses: state.houses,
      title: state.title.trim() || "Untitled Handmade Board",
      seed: `editor-${Date.now()}-${Math.random()}`,
      maxAttempts: state.size === 11 ? 3_000 : 4_000,
    });
    render();
  }

  function handleWorkerMessage(event) {
    const message = event.data;
    if (message.type === "startup-error") {
      startCompatibilityCompletion();
    } else if (message.type === "generation-progress") {
      const candidateLabel = message.progress.candidateMaximum > 1 ? `Candidate ${message.progress.candidate} of ${message.progress.candidateMaximum} · ` : "";
      progress = `${candidateLabel}attempt ${message.progress.attempt} of ${message.progress.maximum}`;
      render();
    } else if (message.type === "analysis-started") {
      result = message.generated;
      busyMessage = "Checking logical difficulty…";
      progress = `${message.candidateMaximum > 1 ? `Candidate ${message.candidate} of ${message.candidateMaximum} · ` : ""}testing the basic rules`;
      render();
    } else if (message.type === "difficulty-progress") {
      const detail = message.progress.technique || "logical techniques";
      const candidateLabel = message.progress.candidateMaximum > 1 ? `Candidate ${message.progress.candidate} of ${message.progress.candidateMaximum} · ` : "";
      progress = `${candidateLabel}${message.progress.percent ?? 0}% · ${detail}`;
      render();
    } else if (message.type === "candidate-rejected") {
      result = null;
      busyMessage = "Trying a more logically solvable completion…";
      progress = `The unique candidate ${message.candidate} of ${message.candidateMaximum} was incalculable`;
      render();
    } else if (message.type === "completed") {
      result = message.generated;
      difficulty = message.difficulty;
      if (!difficulty.solved || difficulty.label === "Incalculable") {
        notice = { kind: "error", message: "The board is unique, but the logical analyzer could not finish it. Try another completion." };
      } else {
        notice = { kind: "success", message: "Unique solution confirmed. This board is ready to export." };
      }
      stopWorker();
      render();
    } else if (message.type === "error") {
      finishWithError(message.message);
    }
  }

  function startCompatibilityCompletion() {
    stopWorker();
    let cancelled = false;
    const compatibilityJob = {
      terminate() { cancelled = true; },
    };
    worker = compatibilityJob;
    busyMessage = "Constructing the missing houses…";
    progress = "Using browser compatibility mode";
    render();

    setTimeout(async () => {
      try {
        const boardIsFullyPainted = state.houses.every((row) => row.every((house) => house >= 0));
        const boardIsBlank = state.houses.every((row) => row.every((house) => house === -1));
        const candidateMaximum = boardIsFullyPainted ? 1 : boardIsBlank ? 12 : 8;
        const seed = `editor-${Date.now()}-${Math.random()}`;
        const maxAttempts = state.size === 11 ? 3_000 : 4_000;
        let lastResult = null;

        for (let candidate = 1; candidate <= candidateMaximum && !cancelled; candidate += 1) {
          const generated = globalThis.StarsRemixEngine.completePuzzleFromHouses(state.houses, {
            title: state.title.trim() || "Untitled Handmade Board",
            seed: `${seed}-candidate-${candidate}`,
            maxAttempts,
            onProgress(update) {
              progress = `${candidateMaximum > 1 ? `Candidate ${candidate} of ${candidateMaximum} · ` : ""}attempt ${update.attempt} of ${update.maximum}`;
            },
          });
          if (cancelled) return;

          result = generated;
          busyMessage = "Checking logical difficulty…";
          progress = `${candidateMaximum > 1 ? `Candidate ${candidate} of ${candidateMaximum} · ` : ""}testing the basic rules`;
          render();
          const report = await globalThis.StarsRemixHints.analyzeDifficulty(generated.puzzle, {
            onProgress(update) {
              progress = `${candidateMaximum > 1 ? `Candidate ${candidate} of ${candidateMaximum} · ` : ""}${update.percent ?? 0}% · ${update.technique || "logical techniques"}`;
            },
            yieldControl: () => new Promise((resolve) => setTimeout(resolve, 0)),
          });
          if (cancelled) return;

          lastResult = { generated, report };
          if (report.solved && report.label !== "Incalculable") break;
          if (candidate < candidateMaximum) {
            result = null;
            busyMessage = "Trying a more logically solvable completion…";
            progress = `The unique candidate ${candidate} of ${candidateMaximum} was incalculable`;
            render();
            await new Promise((resolve) => setTimeout(resolve, 0));
          }
        }

        if (cancelled || worker !== compatibilityJob) return;
        const { generated, report } = lastResult;
        handleWorkerMessage({
          data: {
            type: "completed",
            generated,
            difficulty: {
              solved: report.solved,
              label: report.label,
              score: report.score,
              bigTicketCount: report.bigTicketCount,
              logicalSteps: report.steps.length,
            },
          },
        });
      } catch (error) {
        if (!cancelled && worker === compatibilityJob) {
          finishWithError(error instanceof Error ? error.message : "Unable to complete this board.");
        }
      }
    }, 0);
  }

  function exportBoard() {
    if (!result || !difficulty) return;
    const title = state.title.trim();
    if (!title) {
      notice = { kind: "error", message: "Give the board a title before exporting." };
      render();
      return;
    }

    try {
      const id = `handmade-${boardSlug(title)}-${Date.now().toString(36)}`;
      const entry = {
        puzzle: { ...result.puzzle, id, title },
        solution: result.solution,
        difficulty: {
          label: difficulty.label,
          score: difficulty.score,
          bigTicketCount: difficulty.bigTicketCount,
          logicalSteps: difficulty.logicalSteps,
        },
        source: "handmade",
      };
      const filename = `${id}.json`;
      downloadJson(filename, entry);
      exported = { filename, entry };
      result.puzzle.id = id;
      result.puzzle.title = title;
      notice = { kind: "success", message: "Board JSON downloaded." };
    } catch (error) {
      notice = { kind: "error", message: error instanceof Error ? error.message : "Unable to export this board." };
    }
    render();
  }

  function downloadJson(filename, value) {
    const blob = new Blob([`${JSON.stringify(value, null, 2)}\n`], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.append(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 0);
  }

  function boardSlug(value) {
    return String(value)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "untitled";
  }

  function cancelWork() {
    stopWorker();
    result = null;
    difficulty = null;
    notice = { kind: "info", message: "Completion cancelled. Your painted houses are unchanged." };
    render();
  }

  function finishWithError(message) {
    stopWorker();
    result = null;
    difficulty = null;
    notice = { kind: "error", message };
    render();
  }

  function stopWorker() {
    worker?.terminate();
    worker = null;
    busyMessage = "";
    progress = null;
  }

  function resetResult() {
    result = null;
    difficulty = null;
    exported = null;
    showSolution = false;
    notice = null;
  }

  function escapeHtml(value) {
    return String(value ?? "").replace(/[&<>'"]/g, (character) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;",
    })[character]);
  }

  window.addEventListener("pointerup", () => { painting = false; activePaintHouse = null; });
  window.addEventListener("blur", () => { painting = false; activePaintHouse = null; });
  window.addEventListener("keydown", (event) => {
    if (event.ctrlKey || event.metaKey || event.altKey || event.target.matches("input, select, textarea, [contenteditable]")) return;
    if (!/^\d$/.test(event.key)) return;
    const house = event.key === "0" ? 9 : Number(event.key) - 1;
    if (house >= state.size) return;
    event.preventDefault();
    selectedPaintHouse = house;
    notice = null;
    render();
  });
  render();
})();
